import Head from "next/head";
import Image from "next/image";

import MiniNav from "@/components/Nav/MiniNav";
import MainHero from "@/components/SaleGrid/MainHero";
import MainSaleItem from "@/components/SaleGrid/MainSaleItem";
import SkiBus from "@/components/SkiBus/SkiBus";
import FieldGuides from "@/components/FieldGuide/FieldGuides";

export default function Home() {
  return (
    <>
      <Head>
        <title>SB-Dupe</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/SB_LOGO.svg" />
      </Head>
      {/* web start */}
      {/* <MiniNav /> */}
      <MainHero />
      <MainSaleItem />
      <SkiBus />
      <FieldGuides />
    </>
  );
}
